name: CI Pipeline

on:
  push:
    branches: [main]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: |
          pip install flake8 black

      - name: Run flake8
        run: flake8 src tests

      - name: Check formatting
        run: black --check src tests


  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest tests -v
